#!/usr/bin/env node
// Regenerates packages/core/src/lib/agentic/contracts/abi/e704d5b/*.ts from the
// pinned ABI evidence in plan/agw/research/validation-e704d5b/abi/. The source
// JSON is the reviewed artifact set; this script only re-serialises it as
// `as const` TypeScript so viem can infer types. Run from the repo root:
//   node packages/core/scripts/agw-local/gen-abi.mjs
import { createHash } from 'node:crypto';
import { readFileSync, writeFileSync, mkdirSync } from 'node:fs';
import { dirname, join, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const here = dirname(fileURLToPath(import.meta.url));
const repo = resolve(here, '../../../..');
const src = join(repo, 'plan/agw/research/validation-e704d5b/abi');
const dst = join(repo, 'packages/core/src/lib/agentic/contracts/abi/e704d5b');
const PIN = 'e704d5b58fd1d30ce02bc0ad74dccfbdb37804f9';

const files = {
  AGW: ['AGW_ABI', 'agw.ts'],
  AGWFactory: ['AGW_FACTORY_ABI', 'agw-factory.ts'],
  UniversalRulesPolicy: ['UNIVERSAL_RULES_POLICY_ABI', 'universal-rules-policy.ts'],
  SmartSession: ['SMART_SESSION_ABI', 'smart-session.ts'],
  AgentValidator: ['AGENT_VALIDATOR_ABI', 'agent-validator.ts'],
};

mkdirSync(dst, { recursive: true });
const exports = [];
for (const [name, [constName, file]] of Object.entries(files)) {
  const raw = readFileSync(join(src, `${name}.json`));
  const sha = createHash('sha256').update(raw).digest('hex');
  const abi = JSON.parse(raw.toString()).filter((e) => e.type !== 'constructor');
  const body =
    `// GENERATED by packages/core/scripts/agw-local/gen-abi.mjs — do not edit.\n` +
    `// Source: plan/agw/research/validation-e704d5b/abi/${name}.json\n` +
    `// push-agentic-wallets@${PIN}\n` +
    `// sha256(${name}.json) = ${sha}\n` +
    `export const ${constName} = ${JSON.stringify(abi, null, 2)} as const;\n`;
  writeFileSync(join(dst, file), body);
  exports.push(`export { ${constName} } from './${file.replace(/\.ts$/, '')}';`);
}
writeFileSync(
  join(dst, 'index.ts'),
  `// GENERATED by packages/core/scripts/agw-local/gen-abi.mjs — do not edit.\n` +
    `// Review generation e704d5b: no verified deployment exists for this ABI set.\n` +
    `export const E704D5B_SOURCE_COMMIT = '${PIN}' as const;\n` +
    exports.join('\n') +
    '\n'
);
console.log(`wrote ${Object.keys(files).length} ABI modules to ${dst}`);
