#!/usr/bin/env node
// Regenerates packages/core/src/lib/agentic/contracts/abi/v4/*.ts from the
// pinned ABI snapshots in ./abis/. The JSON files are the source artifact set;
// this script only re-serialises them as
// `as const` TypeScript so viem can infer types. Run from the repo root:
//   node packages/core/scripts/agw-local/gen-abi.mjs
import { createHash } from 'node:crypto';
import { readFileSync, writeFileSync, mkdirSync } from 'node:fs';
import { dirname, join, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const here = dirname(fileURLToPath(import.meta.url));
const repo = resolve(here, '../../../..');
const src = join(here, 'abis');
const dst = join(repo, 'packages/core/src/lib/agentic/contracts/abi/v4');
const PIN = 'e8db74815cfbbf5389593805e464fe8d85f7f735';

const sourceNames = {
  AGW: 'wallet',
  AGWFactory: 'factory',
  UniversalRulesPolicy: 'policy',
  SmartSession: 'engine',
  AgentValidator: 'validator',
};
const files = {
  AGW: ['AGW_ABI', 'agw.ts'],
  AGWFactory: ['AGW_FACTORY_ABI', 'agw-factory.ts'],
  UniversalRulesPolicy: [
    'UNIVERSAL_RULES_POLICY_ABI',
    'universal-rules-policy.ts',
  ],
  SmartSession: ['SMART_SESSION_ABI', 'smart-session.ts'],
  AgentValidator: ['AGENT_VALIDATOR_ABI', 'agent-validator.ts'],
};
const manifest = JSON.parse(readFileSync(join(src, 'manifest.json'), 'utf8'));

mkdirSync(dst, { recursive: true });
const exports = [];
for (const [name, [constName, file]] of Object.entries(files)) {
  const sourceFile = `${sourceNames[name]}.json`;
  const raw = readFileSync(join(src, sourceFile));
  const sha = createHash('sha256').update(raw).digest('hex');
  if (sha !== manifest.files[sourceFile]) {
    throw new Error(`ABI source hash mismatch: ${sourceFile}`);
  }
  const abi = JSON.parse(raw.toString()).filter(
    (e) => e.type !== 'constructor'
  );
  const body =
    `// GENERATED by packages/core/scripts/agw-local/gen-abi.mjs — do not edit.\n` +
    `// Source: packages/core/scripts/agw-local/abis/${sourceFile}\n` +
    `// push-agentic-wallets@${PIN}\n` +
    `// sha256(${name}.json) = ${sha}\n` +
    `export const ${constName} = ${JSON.stringify(abi, null, 2)} as const;\n`;
  writeFileSync(join(dst, file), body);
  exports.push(
    `export { ${constName} } from './${file.replace(/\.ts$/, '')}';`
  );
}
writeFileSync(
  join(dst, 'index.ts'),
  `// GENERATED by packages/core/scripts/agw-local/gen-abi.mjs — do not edit.\n` +
    `// Review generation v4: Donut v4 deployment; source e8db748.\n` +
    `export const V4_SOURCE_COMMIT = '${PIN}' as const;\n` +
    exports.join('\n') +
    '\n'
);
console.log(`wrote ${Object.keys(files).length} ABI modules to ${dst}`);
