const fs=require('fs'),path=require('path'),crypto=require('crypto');const root=process.cwd();const {createPublicClient,http,parseAbi}=require(path.join(root,'node_modules/viem'));
const prior=JSON.parse(fs.readFileSync('plan/agw/research/deployment-review-2026-10-06/donut-probe.json'));
prior.code.factory.address='0x8137F96A50EBF41d904e3678c84c391a0D1BCcc5'; prior.code.factoryLogic.address='0xe549d3D4e85cB16F687448D7acA21D9d13A7cD0f'; prior.code.walletImplementation.address='0x4D459Da499C14548aa16c46c57fD92880A88EBb4';
const client=createPublicClient({transport:http(prior.rpc)});
(async()=>{const block=await client.getBlock();const result={checked_at:new Date().toISOString(),rpc:prior.rpc,chain_id:await client.getChainId(),block:String(block.number),block_hash:block.hash,code:{},slots:{},reads:[]};
await Promise.all(Object.entries(prior.code).map(async([name,item])=>{const data=await client.getCode({address:item.address,blockNumber:block.number})||'0x';const bytes=Buffer.from(data.slice(2),'hex');const sha256=crypto.createHash('sha256').update(bytes).digest('hex');result.code[name]={address:item.address,bytes:bytes.length,sha256,unchanged:sha256===item.sha256};}));
const slots={implementation:'0x360894a13ba1a3210667c828492db98dca3e2076cc3735a920a3ca505d382bbc',admin:'0xb53127684a568b3173ae13b9f8a6016e243e63b6e8ee1178d6a717850b5d6103'};
for(const [name,rows]of Object.entries(prior.slots)){result.slots[name]={};for(const [kind,value]of Object.entries(rows)){const actual=await client.getStorageAt({address:prior.code[name].address,slot:slots[kind],blockNumber:block.number});result.slots[name][kind]={value:actual,unchanged:actual?.toLowerCase()===value.toLowerCase()};}}
for(const row of prior.reads){const name=row.signature.split('(')[0],type=row.signature.split(')(')[1].slice(0,-1);try{const value=await client.readContract({address:prior.code[row.contract].address,abi:parseAbi([`function ${name}() view returns (${type})`]),functionName:name,blockNumber:block.number});result.reads.push({contract:row.contract,signature:row.signature,value:String(value),unchanged:String(value).toLowerCase()===row.output.replaceAll('"','').toLowerCase()});}catch(e){result.reads.push({contract:row.contract,signature:row.signature,error:e.shortMessage||e.message});}}
fs.writeFileSync('plan/agw/research/deployment-review-2026-10-07-v5/donut-probe.json',JSON.stringify(result,null,2)+'\n');console.log(JSON.stringify({block:result.block,codeChanged:Object.entries(result.code).filter(([,v])=>!v.unchanged).map(([k])=>k),slots:result.slots,readMismatches:result.reads.filter(r=>!r.unchanged)}));})();
