// GENERATED by packages/core/scripts/agw-local/gen-abi.mjs — do not edit.
// Source: plan/agw/research/deployment-review-2026-10-06/abis/AgentValidator.json
// push-agentic-wallets@e8db74815cfbbf5389593805e464fe8d85f7f735
// sha256(AgentValidator.json) = d2555b2f54d56ed24268af650b19ad10f2d34906b2e0c4ff78dd6de54ba34cc2
export const AGENT_VALIDATOR_ABI = [
  {
    "inputs": [
      {
        "internalType": "address",
        "name": "smartAccount",
        "type": "address"
      }
    ],
    "name": "AlreadyInitialized",
    "type": "error"
  },
  {
    "inputs": [],
    "name": "MalformedConfig",
    "type": "error"
  },
  {
    "inputs": [
      {
        "internalType": "address",
        "name": "smartAccount",
        "type": "address"
      }
    ],
    "name": "NotInitialized",
    "type": "error"
  },
  {
    "inputs": [
      {
        "internalType": "address",
        "name": "",
        "type": "address"
      }
    ],
    "name": "isInitialized",
    "outputs": [
      {
        "internalType": "bool",
        "name": "",
        "type": "bool"
      }
    ],
    "stateMutability": "pure",
    "type": "function"
  },
  {
    "inputs": [
      {
        "internalType": "uint256",
        "name": "moduleTypeId",
        "type": "uint256"
      }
    ],
    "name": "isModuleType",
    "outputs": [
      {
        "internalType": "bool",
        "name": "",
        "type": "bool"
      }
    ],
    "stateMutability": "pure",
    "type": "function"
  },
  {
    "inputs": [
      {
        "internalType": "bytes",
        "name": "",
        "type": "bytes"
      }
    ],
    "name": "onInstall",
    "outputs": [],
    "stateMutability": "pure",
    "type": "function"
  },
  {
    "inputs": [
      {
        "internalType": "bytes",
        "name": "",
        "type": "bytes"
      }
    ],
    "name": "onUninstall",
    "outputs": [],
    "stateMutability": "pure",
    "type": "function"
  },
  {
    "inputs": [
      {
        "internalType": "bytes",
        "name": "data",
        "type": "bytes"
      }
    ],
    "name": "validateConfig",
    "outputs": [
      {
        "internalType": "bool",
        "name": "",
        "type": "bool"
      }
    ],
    "stateMutability": "pure",
    "type": "function"
  },
  {
    "inputs": [
      {
        "internalType": "bytes32",
        "name": "",
        "type": "bytes32"
      },
      {
        "internalType": "bytes",
        "name": "sig",
        "type": "bytes"
      },
      {
        "internalType": "bytes",
        "name": "data",
        "type": "bytes"
      }
    ],
    "name": "validateSignatureWithData",
    "outputs": [
      {
        "internalType": "bool",
        "name": "validSig",
        "type": "bool"
      }
    ],
    "stateMutability": "pure",
    "type": "function"
  }
] as const;
